Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,7 +1,7 @@
 name: Build and Deploy to ECR
 
 on:
-  push:
+  pull_request:
     branches:
       - main
 
@@ -42,9 +42,24 @@ jobs:
           name: unit-test-results
           path: target/surefire-reports/
 
-  integration-tests:
+  coverage:
     runs-on: ubuntu-latest
     needs: unit-tests
+
+    steps:    
+      - name: Fetch Quality Gate Result
+        run: |
+          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=FIAP-6SOAT-G10_fiap-fast-food-ms-produto" | jq -r '.projectStatus.status')
+          if [ "$STATUS" != "OK" ]; then
+            echo "SonarQube Quality Gate failed."
+            exit 1
+          fi
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+  integration-tests:
+    runs-on: ubuntu-latest
+    needs: coverage
 
     steps:
       - name: Checkout code
